# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='/var/www/ShortVideo/media/avatar', verbose_name='用戶頭像'),
        ),
    ]
