# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import video.models
import videokit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', videokit.models.VideoField(duration_field='video_duration', height_field='video_height', mimetype_field='video_mimetype', rotation_field='video_rotation', thumbnail_field='video_thumbnail', upload_to=video.models.upload_to, width_field='video_width')),
                ('video_width', models.IntegerField(blank=True, null=True)),
                ('video_height', models.IntegerField(blank=True, null=True)),
                ('video_rotation', models.FloatField(blank=True, null=True)),
                ('video_mimetype', models.CharField(blank=True, max_length=32, null=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_mp4', videokit.models.VideoSpecField(blank=True, null=True, upload_to='')),
                ('video_ogg', videokit.models.VideoSpecField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
